service: pilot-test
app: segurired-alpha
org: lupnox

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

#environment variables here
  environment:
    THINGS_URL: 'http://ec2-3-101-90-91.us-west-1.compute.amazonaws.com:8080/'

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**


functions:
  requestRPC:
    handler: lambdas/rpcRequest.sendRPC
