service: pilot-test
app: segurired-alpha
org: lupnox

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev
  iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/registroAVP"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/alarmas"

functions:
  responder:
    handler: llamadaEntrante.handler
    events:
            - http:
                  path: responder
                  method: POST
                  cors: true