service: pilot-test
app: segurired-alpha
org: lupnox

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev
  iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/registroAVP"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/alarmas"
        - Effect: Allow
          Action: 
              - secretsmanager:GetSecretValue
              - secretsmanager:PutSecretValue
          Resource:
            - "arn:aws:secretsmanager:us-west-1:793033367648:secret:TB/RPCAuth-ekj9pb"
  
  #environment variables here
  environment:
    REGION:          "${opt:region, self:provider.region}"
    THINGS_URL:      "http://ec2-3-101-90-91.us-west-1.compute.amazonaws.com:8080/"
    AWS_EX_URL:      "https://l19mq6u0x5.execute-api.us-west-1.amazonaws.com/TBparams"
    GATHER_URL:      "${self:provider.environment.AWS_EX_URL}/handleGather"
    FINISH_CALL_URL: "${self:provider.environment.AWS_EX_URL}/finishCall"
    SEND_TG_MSG_URL: "${self:provider.environment.AWS_EX_URL}/sendRecordedMsg"

functions:
  responder:
    handler: lambdas/twilio/llamadaEntrante.handler
    events:
            - http:
                  path: responder
                  method: POST
                  cors: true
  handleGather:
    handler: lambdas/twilio/handleGather.handler
    events:
            - http:
                  path: handleGather
                  method: POST
                  cors: true
  finishCall:
    handler: lambdas/twilio/finishCall.handler
    events:
            - http:
                  path: finishCall
                  method: POST
                  cors: true
  refreshTBT:
    handler: lambdas/thingsBoard/refreshTBT.refreshTBToken
    timeout: 15
    events:
            - http:
                  path: refreshTBT
                  method: GET
                  cors: true
            - schedule:
                  rate: rate(7 minutes) 
                  enabled: true 
  sendRecordedMsg:
    handler: lambdas/telegram/sendRecordedMsg.handler
    events:
            - http:
                  path: sendRecordedMsg
                  method: POST
                  cors: true

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**
