service: pilot-test
app: segurired-alpha
org: lupnox

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev
  iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/registroAVP"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/alarmas"
        - Effect: Allow
          Action: 
              - secretsmanager:GetSecretValue
              - secretsmanager:PutSecretValue
          Resource:
            - "arn:aws:secretsmanager:us-west-1:793033367648:secret:TB/RPCAuth-ekj9pb"
  
  #environment variables here
  environment:
    THINGS_URL: 'http://ec2-3-101-90-91.us-west-1.compute.amazonaws.com:8080/'
    REGION: "${opt:region, self:provider.region}"

functions:
  responder:
    handler: lambdas/twilio/llamadaEntrante.handler
    events:
            - http:
                  path: responder
                  method: POST
                  cors: true
  handleGather:
    handler: lambdas/twilio/handleGather.handler
    events:
            - http:
                  path: handleGather
                  method: POST
                  cors: true
  refreshTBT:
    handler: lambdas/thingsBoard/refreshTBT.refreshTBToken
    timeout: 15
    events:
            - http:
                  path: refreshTBT
                  method: GET
                  cors: true



# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**
